### ISSUE TITLE
Enable Geo module.

### ISSUE THREAD

**Issue by skid9000** [Angristan/nginx-autoinstall#27]
Hello,

Can you enable the Geo module by default ?

Thanks.
Skid

**Comment by Angristan** [comment]
What do you mean ?

**Comment by skid9000** [comment]
Line 413, change `--without-http_geo_module \` by `--with-http_geo_module \`

**Comment by Angristan** [comment]
You can choose to enable the module during the setup

**Comment by skid9000** [comment]
Nope, GeoIP and Geo are not the same module o/

**Comment by Angristan** [comment]
Oh right ! Sorry.
Well afaik, it's rarely used, so I won't enable it. But you can modify the script on your side to compile with this module. :)

**Comment by online-expert** [comment]
First of all thanks for this awesome script!
Default installation gives problems in combination with nginx-ultimate-bad-bot-blocker since it needs geo_module. https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker 
Enabling geo_module by default would be easier but modifying the script as suggested indeed also solved the problem. 
I hope this info helps other people searching for combination nginx-autoinstall nginx-ultimate-bad-bot-blocker geo_module.

**Comment by luison** [comment]
I am at the same position. Geo module assigns variables based on IPs and I understand included in most Nginx package  flavours. I'll also change the script but perhaps you could consider. Thanks.

**Comment by angristan** [comment]
Fixed
